@echo off
Echo Switching emulator to Application Shell start
attrib -r \EPOC32\RELEASE\WINS\UDEB\Z\SYSTEM\PROGRAMS\STARTER.RSC
attrib -r \EPOC32\INCLUDE\STARTER.RSG
attrib -r \EPOC32\RELEASE\WINS\UREL\Z\SYSTEM\PROGRAMS\STARTER.RSC

copy \epoc32\tools\STARTER_SHELL.RSC \EPOC32\RELEASE\WINS\UDEB\Z\SYSTEM\PROGRAMS\STARTER.RSC
copy \epoc32\tools\STARTER_SHELL.RSC \EPOC32\RELEASE\WINS\UREL\Z\SYSTEM\PROGRAMS\STARTER.RSC
copy \epoc32\tools\STARTER_SHELL.RSG \EPOC32\INCLUDE\STARTER.RSG
